# harness.io/skip-file-for-deploy

apiVersion: batch/v1
kind: Job
metadata:
  name: {{.Values.name}}-secrets
spec:
  template:
    spec:
      containers:
      - name: {{.Values.name}}-secrets
        image:
        command: []
        resources:
          requests:
            cpu:
            memory:
          limits:
            cpu:
            memory:
        envFrom:
        - secretRef:
            name:
        - configMapRef:
            name:
        securityContext:
          privileged: true
      restartPolicy: